services:
  - type: web
    name: resume-ai-backend
    env: python
    rootDir: backend
    runtime: python-3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT